# Generated by Django 5.0.7 on 2025-02-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfiniteRide', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='identity',
        ),
    ]
