# Generated by Django 5.1.6 on 2025-02-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfiniteRide', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('available', models.BooleanField(default=True)),
                ('engine_capacity', models.FloatField()),
                ('bike_type', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('available', models.BooleanField(default=True)),
                ('seating_capacity', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('transmission_type', models.CharField(max_length=50)),
                ('needs_driver', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LargeVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('available', models.BooleanField(default=True)),
                ('seating_capacity', models.IntegerField()),
                ('needs_driver', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
