# Generated by Django 5.1.6 on 2025-02-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfiniteRide', '0006_bike_car_largevehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='featured_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='featured_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='largevehicle',
            name='featured_vehicle',
            field=models.BooleanField(default=False),
        ),
    ]
