# Generated by Django 5.1.6 on 2025-02-11 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfiniteRide', '0008_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='dropoff_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_dropoff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
