# Generated by Django 5.1.6 on 2025-02-13 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfiniteRide', '0011_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='dropoff_address',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='license_image',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_dropoff',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='self_drive',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='special_requirements',
        ),
        migrations.AlterField(
            model_name='booking',
            name='bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InfiniteRide.bike'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InfiniteRide.car'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='large_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='InfiniteRide.largevehicle'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_days',
            field=models.PositiveIntegerField(),
        ),
    ]
