# Generated by Django 5.1.6 on 2025-02-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfiniteRide', '0012_remove_booking_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='drop_off_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='drop_off_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='licenses/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='self_drive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
