# Generated by Django 5.1.6 on 2025-02-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfiniteRide', '0014_booking_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='special_requests',
            new_name='special_requirements',
        ),
    ]
