# Generated by Django 5.1.6 on 2025-02-14 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfiniteRide', '0015_rename_special_requests_booking_special_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('self_drive', models.BooleanField(default=False)),
                ('dropoff_required', models.BooleanField(default=False)),
                ('dropoff_address', models.CharField(blank=True, max_length=255, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='InfiniteRide.booking')),
            ],
        ),
    ]
