# Generated by Django 5.1.6 on 2025-02-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfiniteRide', '0017_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
