# Generated by Django 5.1.6 on 2025-02-17 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfiniteRide', '0019_booking_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='dropoff_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='dropoff_required',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='self_drive',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user_phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('is_visible_to_admin', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='InfiniteRide.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
