# Generated by Django 5.1.6 on 2025-02-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfiniteRide', '0020_remove_invoice_dropoff_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
