# Generated by Django 5.1.6 on 2025-02-17 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfiniteRide', '0021_review_review_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_visible_to_admin',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_submitted',
        ),
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='InfiniteRide.booking'),
        ),
    ]
