# Generated by Django 5.1.6 on 2025-02-17 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InfiniteRide', '0022_remove_review_is_visible_to_admin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
