# Generated by Django 5.1.6 on 2025-03-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfiniteRide', '0028_alter_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(),
        ),
    ]
