# Generated by Django 5.1.6 on 2025-04-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfiniteRide', '0029_alter_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='confirmation_time',
            field=models.DateTimeField(auto_now_add=True, default='2025-04-20 20:30:00'),
            preserve_default=False,
        ),
    ]
