# Generated by Django 5.1.6 on 2025-04-21 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfiniteRide', '0030_bill_confirmation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_seen_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
