# Generated by Django 5.1.6 on 2025-04-21 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfiniteRide', '0031_booking_booking_date_booking_is_seen_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='confirmation_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='bill',
            name='confirmation_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
